# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft/generic/pointers/v1/object_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft.types.torch.v1 import script_module_pb2 as pysyft_dot_types_dot_torch_dot_v1_dot_script__module__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft/generic/pointers/v1/object_wrapper.proto',
  package='pysyft.generic.pointers.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/pysyft/generic/pointers/v1/object_wrapper.proto\x12\x1apysyft.generic.pointers.v1\x1a)pysyft/types/torch/v1/script_module.proto\"}\n\rObjectWrapper\x12\x19\n\x07\x61rg_int\x18\x01 \x01(\x05H\x00R\x06\x61rgInt\x12J\n\rscript_module\x18\x02 \x01(\x0b\x32#.pysyft.types.torch.v1.ScriptModuleH\x00R\x0cscriptModuleB\x05\n\x03\x61rgb\x06proto3')
  ,
  dependencies=[pysyft_dot_types_dot_torch_dot_v1_dot_script__module__pb2.DESCRIPTOR,])




_OBJECTWRAPPER = _descriptor.Descriptor(
  name='ObjectWrapper',
  full_name='pysyft.generic.pointers.v1.ObjectWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg_int', full_name='pysyft.generic.pointers.v1.ObjectWrapper.arg_int', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='argInt', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_module', full_name='pysyft.generic.pointers.v1.ObjectWrapper.script_module', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='scriptModule', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='arg', full_name='pysyft.generic.pointers.v1.ObjectWrapper.arg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=122,
  serialized_end=247,
)

_OBJECTWRAPPER.fields_by_name['script_module'].message_type = pysyft_dot_types_dot_torch_dot_v1_dot_script__module__pb2._SCRIPTMODULE
_OBJECTWRAPPER.oneofs_by_name['arg'].fields.append(
  _OBJECTWRAPPER.fields_by_name['arg_int'])
_OBJECTWRAPPER.fields_by_name['arg_int'].containing_oneof = _OBJECTWRAPPER.oneofs_by_name['arg']
_OBJECTWRAPPER.oneofs_by_name['arg'].fields.append(
  _OBJECTWRAPPER.fields_by_name['script_module'])
_OBJECTWRAPPER.fields_by_name['script_module'].containing_oneof = _OBJECTWRAPPER.oneofs_by_name['arg']
DESCRIPTOR.message_types_by_name['ObjectWrapper'] = _OBJECTWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectWrapper = _reflection.GeneratedProtocolMessageType('ObjectWrapper', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTWRAPPER,
  '__module__' : 'pysyft.generic.pointers.v1.object_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.generic.pointers.v1.ObjectWrapper)
  })
_sym_db.RegisterMessage(ObjectWrapper)


# @@protoc_insertion_point(module_scope)
