# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft/messaging/v1/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft.types.syft.v1 import id_pb2 as pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2
from pysyft.types.syft.v1 import operation_pb2 as pysyft_dot_types_dot_syft_dot_v1_dot_operation__pb2
from pysyft.types.syft.v1 import pointer_tensor_pb2 as pysyft_dot_types_dot_syft_dot_v1_dot_pointer__tensor__pb2
from pysyft.types.syft.v1 import tensor_pb2 as pysyft_dot_types_dot_syft_dot_v1_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft/messaging/v1/message.proto',
  package='pysyft.messaging.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!pysyft/messaging/v1/message.proto\x12\x13pysyft.messaging.v1\x1a\x1dpysyft/types/syft/v1/id.proto\x1a$pysyft/types/syft/v1/operation.proto\x1a)pysyft/types/syft/v1/pointer_tensor.proto\x1a!pysyft/types/syft/v1/tensor.proto\"Q\n\x18\x46orceObjectDeleteMessage\x12\x35\n\tobject_id\x18\x01 \x01(\x0b\x32\x18.pysyft.types.syft.v1.IdR\x08objectId\"N\n\x0fGetShapeMessage\x12;\n\x06tensor\x18\x01 \x01(\x0b\x32#.pysyft.types.syft.v1.PointerTensorR\x06tensor\"L\n\rIsNoneMessage\x12;\n\x06tensor\x18\x01 \x01(\x0b\x32#.pysyft.types.syft.v1.PointerTensorR\x06tensor\"E\n\rObjectMessage\x12\x34\n\x06tensor\x18\x01 \x01(\x0b\x32\x1c.pysyft.types.syft.v1.TensorR\x06tensor\"M\n\x14ObjectRequestMessage\x12\x35\n\tobject_id\x18\x01 \x01(\x0b\x32\x18.pysyft.types.syft.v1.IdR\x08objectId\"Q\n\x10OperationMessage\x12=\n\toperation\x18\x01 \x01(\x0b\x32\x1f.pysyft.types.syft.v1.OperationR\toperation\"l\n\x12PlanCommandMessage\x12\x18\n\x07\x63ommand\x18\x01 \x01(\tR\x07\x63ommand\x12(\n\x02id\x18\x02 \x01(\x0b\x32\x18.pysyft.types.syft.v1.IdR\x02id\x12\x12\n\x04\x63opy\x18\x03 \x01(\x08R\x04\x63opy\"0\n\rSearchMessage\x12\x1f\n\x0bquery_terms\x18\x01 \x03(\tR\nqueryTermsb\x06proto3')
  ,
  dependencies=[pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2.DESCRIPTOR,pysyft_dot_types_dot_syft_dot_v1_dot_operation__pb2.DESCRIPTOR,pysyft_dot_types_dot_syft_dot_v1_dot_pointer__tensor__pb2.DESCRIPTOR,pysyft_dot_types_dot_syft_dot_v1_dot_tensor__pb2.DESCRIPTOR,])




_FORCEOBJECTDELETEMESSAGE = _descriptor.Descriptor(
  name='ForceObjectDeleteMessage',
  full_name='pysyft.messaging.v1.ForceObjectDeleteMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='pysyft.messaging.v1.ForceObjectDeleteMessage.object_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='objectId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=286,
)


_GETSHAPEMESSAGE = _descriptor.Descriptor(
  name='GetShapeMessage',
  full_name='pysyft.messaging.v1.GetShapeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='pysyft.messaging.v1.GetShapeMessage.tensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tensor', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=366,
)


_ISNONEMESSAGE = _descriptor.Descriptor(
  name='IsNoneMessage',
  full_name='pysyft.messaging.v1.IsNoneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='pysyft.messaging.v1.IsNoneMessage.tensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tensor', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=444,
)


_OBJECTMESSAGE = _descriptor.Descriptor(
  name='ObjectMessage',
  full_name='pysyft.messaging.v1.ObjectMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='pysyft.messaging.v1.ObjectMessage.tensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tensor', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=515,
)


_OBJECTREQUESTMESSAGE = _descriptor.Descriptor(
  name='ObjectRequestMessage',
  full_name='pysyft.messaging.v1.ObjectRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='pysyft.messaging.v1.ObjectRequestMessage.object_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='objectId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=594,
)


_OPERATIONMESSAGE = _descriptor.Descriptor(
  name='OperationMessage',
  full_name='pysyft.messaging.v1.OperationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='pysyft.messaging.v1.OperationMessage.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='operation', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=677,
)


_PLANCOMMANDMESSAGE = _descriptor.Descriptor(
  name='PlanCommandMessage',
  full_name='pysyft.messaging.v1.PlanCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='pysyft.messaging.v1.PlanCommandMessage.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='command', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='pysyft.messaging.v1.PlanCommandMessage.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='copy', full_name='pysyft.messaging.v1.PlanCommandMessage.copy', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='copy', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=787,
)


_SEARCHMESSAGE = _descriptor.Descriptor(
  name='SearchMessage',
  full_name='pysyft.messaging.v1.SearchMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_terms', full_name='pysyft.messaging.v1.SearchMessage.query_terms', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='queryTerms', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=789,
  serialized_end=837,
)

_FORCEOBJECTDELETEMESSAGE.fields_by_name['object_id'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_GETSHAPEMESSAGE.fields_by_name['tensor'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_pointer__tensor__pb2._POINTERTENSOR
_ISNONEMESSAGE.fields_by_name['tensor'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_pointer__tensor__pb2._POINTERTENSOR
_OBJECTMESSAGE.fields_by_name['tensor'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_tensor__pb2._TENSOR
_OBJECTREQUESTMESSAGE.fields_by_name['object_id'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_OPERATIONMESSAGE.fields_by_name['operation'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_operation__pb2._OPERATION
_PLANCOMMANDMESSAGE.fields_by_name['id'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
DESCRIPTOR.message_types_by_name['ForceObjectDeleteMessage'] = _FORCEOBJECTDELETEMESSAGE
DESCRIPTOR.message_types_by_name['GetShapeMessage'] = _GETSHAPEMESSAGE
DESCRIPTOR.message_types_by_name['IsNoneMessage'] = _ISNONEMESSAGE
DESCRIPTOR.message_types_by_name['ObjectMessage'] = _OBJECTMESSAGE
DESCRIPTOR.message_types_by_name['ObjectRequestMessage'] = _OBJECTREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['OperationMessage'] = _OPERATIONMESSAGE
DESCRIPTOR.message_types_by_name['PlanCommandMessage'] = _PLANCOMMANDMESSAGE
DESCRIPTOR.message_types_by_name['SearchMessage'] = _SEARCHMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForceObjectDeleteMessage = _reflection.GeneratedProtocolMessageType('ForceObjectDeleteMessage', (_message.Message,), {
  'DESCRIPTOR' : _FORCEOBJECTDELETEMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.ForceObjectDeleteMessage)
  })
_sym_db.RegisterMessage(ForceObjectDeleteMessage)

GetShapeMessage = _reflection.GeneratedProtocolMessageType('GetShapeMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETSHAPEMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.GetShapeMessage)
  })
_sym_db.RegisterMessage(GetShapeMessage)

IsNoneMessage = _reflection.GeneratedProtocolMessageType('IsNoneMessage', (_message.Message,), {
  'DESCRIPTOR' : _ISNONEMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.IsNoneMessage)
  })
_sym_db.RegisterMessage(IsNoneMessage)

ObjectMessage = _reflection.GeneratedProtocolMessageType('ObjectMessage', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.ObjectMessage)
  })
_sym_db.RegisterMessage(ObjectMessage)

ObjectRequestMessage = _reflection.GeneratedProtocolMessageType('ObjectRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTREQUESTMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.ObjectRequestMessage)
  })
_sym_db.RegisterMessage(ObjectRequestMessage)

OperationMessage = _reflection.GeneratedProtocolMessageType('OperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.OperationMessage)
  })
_sym_db.RegisterMessage(OperationMessage)

PlanCommandMessage = _reflection.GeneratedProtocolMessageType('PlanCommandMessage', (_message.Message,), {
  'DESCRIPTOR' : _PLANCOMMANDMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.PlanCommandMessage)
  })
_sym_db.RegisterMessage(PlanCommandMessage)

SearchMessage = _reflection.GeneratedProtocolMessageType('SearchMessage', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHMESSAGE,
  '__module__' : 'pysyft.messaging.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.messaging.v1.SearchMessage)
  })
_sym_db.RegisterMessage(SearchMessage)


# @@protoc_insertion_point(module_scope)
