# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft/types/syft/v1/plan_reference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft.types.syft.v1 import id_pb2 as pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft/types/syft/v1/plan_reference.proto',
  package='pysyft.types.syft.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)pysyft/types/syft/v1/plan_reference.proto\x12\x14pysyft.types.syft.v1\x1a\x1dpysyft/types/syft/v1/id.proto\"y\n\rPlanReference\x12\x35\n\tworker_id\x18\x01 \x01(\x0b\x32\x18.pysyft.types.syft.v1.IdR\x08workerId\x12\x31\n\x07plan_id\x18\x02 \x01(\x0b\x32\x18.pysyft.types.syft.v1.IdR\x06planIdb\x06proto3')
  ,
  dependencies=[pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2.DESCRIPTOR,])




_PLANREFERENCE = _descriptor.Descriptor(
  name='PlanReference',
  full_name='pysyft.types.syft.v1.PlanReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='pysyft.types.syft.v1.PlanReference.worker_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workerId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plan_id', full_name='pysyft.types.syft.v1.PlanReference.plan_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='planId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=219,
)

_PLANREFERENCE.fields_by_name['worker_id'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_PLANREFERENCE.fields_by_name['plan_id'].message_type = pysyft_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
DESCRIPTOR.message_types_by_name['PlanReference'] = _PLANREFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlanReference = _reflection.GeneratedProtocolMessageType('PlanReference', (_message.Message,), {
  'DESCRIPTOR' : _PLANREFERENCE,
  '__module__' : 'pysyft.types.syft.v1.plan_reference_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.types.syft.v1.PlanReference)
  })
_sym_db.RegisterMessage(PlanReference)


# @@protoc_insertion_point(module_scope)
