# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft_proto/frameworks/torch/tensors/interpreters/v1/paillier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft_proto.types.syft.v1 import id_pb2 as pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2
from pysyft_proto.generic.v1 import tensor_pb2 as pysyft__proto_dot_generic_dot_v1_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft_proto/frameworks/torch/tensors/interpreters/v1/paillier.proto',
  package='pysyft_proto.frameworks.torch.tensors.interpreters.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nDpysyft_proto/frameworks/torch/tensors/interpreters/v1/paillier.proto\x12\x35pysyft_proto.frameworks.torch.tensors.interpreters.v1\x1a#pysyft_proto/types/syft/v1/id.proto\x1a$pysyft_proto/generic/v1/tensor.proto\"w\n\x0ePaillierTensor\x12.\n\x02id\x18\x01 \x01(\x0b\x32\x1e.pysyft_proto.types.syft.v1.IdR\x02id\x12\x35\n\x05\x63hain\x18\x02 \x01(\x0b\x32\x1f.pysyft_proto.generic.v1.TensorR\x05\x63hainb\x06proto3')
  ,
  dependencies=[pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2.DESCRIPTOR,pysyft__proto_dot_generic_dot_v1_dot_tensor__pb2.DESCRIPTOR,])




_PAILLIERTENSOR = _descriptor.Descriptor(
  name='PaillierTensor',
  full_name='pysyft_proto.frameworks.torch.tensors.interpreters.v1.PaillierTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pysyft_proto.frameworks.torch.tensors.interpreters.v1.PaillierTensor.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain', full_name='pysyft_proto.frameworks.torch.tensors.interpreters.v1.PaillierTensor.chain', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='chain', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=321,
)

_PAILLIERTENSOR.fields_by_name['id'].message_type = pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_PAILLIERTENSOR.fields_by_name['chain'].message_type = pysyft__proto_dot_generic_dot_v1_dot_tensor__pb2._TENSOR
DESCRIPTOR.message_types_by_name['PaillierTensor'] = _PAILLIERTENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaillierTensor = _reflection.GeneratedProtocolMessageType('PaillierTensor', (_message.Message,), {
  'DESCRIPTOR' : _PAILLIERTENSOR,
  '__module__' : 'pysyft_proto.frameworks.torch.tensors.interpreters.v1.paillier_pb2'
  # @@protoc_insertion_point(class_scope:pysyft_proto.frameworks.torch.tensors.interpreters.v1.PaillierTensor)
  })
_sym_db.RegisterMessage(PaillierTensor)


# @@protoc_insertion_point(module_scope)
