// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syft_proto/types/torch/v1/parameter.proto

package syft_proto.types.torch.v1;

public final class ParameterOuterClass {
  private ParameterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:syft_proto.types.torch.v1.Parameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    boolean hasId();
    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    syft_proto.types.syft.v1.IdOuterClass.Id getId();
    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder getIdOrBuilder();

    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    boolean hasTensor();
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    syft_proto.types.torch.v1.Tensor.TorchTensor getTensor();
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getTensorOrBuilder();

    /**
     * <code>bool requires_grad = 3[json_name = "requiresGrad"];</code>
     */
    boolean getRequiresGrad();

    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    boolean hasGrad();
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    syft_proto.types.torch.v1.Tensor.TorchTensor getGrad();
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getGradOrBuilder();
  }
  /**
   * Protobuf type {@code syft_proto.types.torch.v1.Parameter}
   */
  public  static final class Parameter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:syft_proto.types.torch.v1.Parameter)
      ParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Parameter.newBuilder() to construct.
    private Parameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Parameter() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Parameter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Parameter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              syft_proto.types.syft.v1.IdOuterClass.Id.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(syft_proto.types.syft.v1.IdOuterClass.Id.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              syft_proto.types.torch.v1.Tensor.TorchTensor.Builder subBuilder = null;
              if (tensor_ != null) {
                subBuilder = tensor_.toBuilder();
              }
              tensor_ = input.readMessage(syft_proto.types.torch.v1.Tensor.TorchTensor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tensor_);
                tensor_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              requiresGrad_ = input.readBool();
              break;
            }
            case 34: {
              syft_proto.types.torch.v1.Tensor.TorchTensor.Builder subBuilder = null;
              if (grad_ != null) {
                subBuilder = grad_.toBuilder();
              }
              grad_ = input.readMessage(syft_proto.types.torch.v1.Tensor.TorchTensor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(grad_);
                grad_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return syft_proto.types.torch.v1.ParameterOuterClass.internal_static_syft_proto_types_torch_v1_Parameter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return syft_proto.types.torch.v1.ParameterOuterClass.internal_static_syft_proto_types_torch_v1_Parameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              syft_proto.types.torch.v1.ParameterOuterClass.Parameter.class, syft_proto.types.torch.v1.ParameterOuterClass.Parameter.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private syft_proto.types.syft.v1.IdOuterClass.Id id_;
    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    public syft_proto.types.syft.v1.IdOuterClass.Id getId() {
      return id_ == null ? syft_proto.types.syft.v1.IdOuterClass.Id.getDefaultInstance() : id_;
    }
    /**
     * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
     */
    public syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder getIdOrBuilder() {
      return getId();
    }

    public static final int TENSOR_FIELD_NUMBER = 2;
    private syft_proto.types.torch.v1.Tensor.TorchTensor tensor_;
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    public boolean hasTensor() {
      return tensor_ != null;
    }
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    public syft_proto.types.torch.v1.Tensor.TorchTensor getTensor() {
      return tensor_ == null ? syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : tensor_;
    }
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
     */
    public syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getTensorOrBuilder() {
      return getTensor();
    }

    public static final int REQUIRES_GRAD_FIELD_NUMBER = 3;
    private boolean requiresGrad_;
    /**
     * <code>bool requires_grad = 3[json_name = "requiresGrad"];</code>
     */
    public boolean getRequiresGrad() {
      return requiresGrad_;
    }

    public static final int GRAD_FIELD_NUMBER = 4;
    private syft_proto.types.torch.v1.Tensor.TorchTensor grad_;
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    public boolean hasGrad() {
      return grad_ != null;
    }
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    public syft_proto.types.torch.v1.Tensor.TorchTensor getGrad() {
      return grad_ == null ? syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : grad_;
    }
    /**
     * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
     */
    public syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getGradOrBuilder() {
      return getGrad();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (tensor_ != null) {
        output.writeMessage(2, getTensor());
      }
      if (requiresGrad_ != false) {
        output.writeBool(3, requiresGrad_);
      }
      if (grad_ != null) {
        output.writeMessage(4, getGrad());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (tensor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTensor());
      }
      if (requiresGrad_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, requiresGrad_);
      }
      if (grad_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGrad());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof syft_proto.types.torch.v1.ParameterOuterClass.Parameter)) {
        return super.equals(obj);
      }
      syft_proto.types.torch.v1.ParameterOuterClass.Parameter other = (syft_proto.types.torch.v1.ParameterOuterClass.Parameter) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasTensor() != other.hasTensor()) return false;
      if (hasTensor()) {
        if (!getTensor()
            .equals(other.getTensor())) return false;
      }
      if (getRequiresGrad()
          != other.getRequiresGrad()) return false;
      if (hasGrad() != other.hasGrad()) return false;
      if (hasGrad()) {
        if (!getGrad()
            .equals(other.getGrad())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasTensor()) {
        hash = (37 * hash) + TENSOR_FIELD_NUMBER;
        hash = (53 * hash) + getTensor().hashCode();
      }
      hash = (37 * hash) + REQUIRES_GRAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequiresGrad());
      if (hasGrad()) {
        hash = (37 * hash) + GRAD_FIELD_NUMBER;
        hash = (53 * hash) + getGrad().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(syft_proto.types.torch.v1.ParameterOuterClass.Parameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code syft_proto.types.torch.v1.Parameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:syft_proto.types.torch.v1.Parameter)
        syft_proto.types.torch.v1.ParameterOuterClass.ParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return syft_proto.types.torch.v1.ParameterOuterClass.internal_static_syft_proto_types_torch_v1_Parameter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return syft_proto.types.torch.v1.ParameterOuterClass.internal_static_syft_proto_types_torch_v1_Parameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                syft_proto.types.torch.v1.ParameterOuterClass.Parameter.class, syft_proto.types.torch.v1.ParameterOuterClass.Parameter.Builder.class);
      }

      // Construct using syft_proto.types.torch.v1.ParameterOuterClass.Parameter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        if (tensorBuilder_ == null) {
          tensor_ = null;
        } else {
          tensor_ = null;
          tensorBuilder_ = null;
        }
        requiresGrad_ = false;

        if (gradBuilder_ == null) {
          grad_ = null;
        } else {
          grad_ = null;
          gradBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return syft_proto.types.torch.v1.ParameterOuterClass.internal_static_syft_proto_types_torch_v1_Parameter_descriptor;
      }

      @java.lang.Override
      public syft_proto.types.torch.v1.ParameterOuterClass.Parameter getDefaultInstanceForType() {
        return syft_proto.types.torch.v1.ParameterOuterClass.Parameter.getDefaultInstance();
      }

      @java.lang.Override
      public syft_proto.types.torch.v1.ParameterOuterClass.Parameter build() {
        syft_proto.types.torch.v1.ParameterOuterClass.Parameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public syft_proto.types.torch.v1.ParameterOuterClass.Parameter buildPartial() {
        syft_proto.types.torch.v1.ParameterOuterClass.Parameter result = new syft_proto.types.torch.v1.ParameterOuterClass.Parameter(this);
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (tensorBuilder_ == null) {
          result.tensor_ = tensor_;
        } else {
          result.tensor_ = tensorBuilder_.build();
        }
        result.requiresGrad_ = requiresGrad_;
        if (gradBuilder_ == null) {
          result.grad_ = grad_;
        } else {
          result.grad_ = gradBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof syft_proto.types.torch.v1.ParameterOuterClass.Parameter) {
          return mergeFrom((syft_proto.types.torch.v1.ParameterOuterClass.Parameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(syft_proto.types.torch.v1.ParameterOuterClass.Parameter other) {
        if (other == syft_proto.types.torch.v1.ParameterOuterClass.Parameter.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasTensor()) {
          mergeTensor(other.getTensor());
        }
        if (other.getRequiresGrad() != false) {
          setRequiresGrad(other.getRequiresGrad());
        }
        if (other.hasGrad()) {
          mergeGrad(other.getGrad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        syft_proto.types.torch.v1.ParameterOuterClass.Parameter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (syft_proto.types.torch.v1.ParameterOuterClass.Parameter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private syft_proto.types.syft.v1.IdOuterClass.Id id_;
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.syft.v1.IdOuterClass.Id, syft_proto.types.syft.v1.IdOuterClass.Id.Builder, syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder> idBuilder_;
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public syft_proto.types.syft.v1.IdOuterClass.Id getId() {
        if (idBuilder_ == null) {
          return id_ == null ? syft_proto.types.syft.v1.IdOuterClass.Id.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public Builder setId(syft_proto.types.syft.v1.IdOuterClass.Id value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public Builder setId(
          syft_proto.types.syft.v1.IdOuterClass.Id.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public Builder mergeId(syft_proto.types.syft.v1.IdOuterClass.Id value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              syft_proto.types.syft.v1.IdOuterClass.Id.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public syft_proto.types.syft.v1.IdOuterClass.Id.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      public syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              syft_proto.types.syft.v1.IdOuterClass.Id.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.syft_proto.types.syft.v1.Id id = 1[json_name = "id"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.syft.v1.IdOuterClass.Id, syft_proto.types.syft.v1.IdOuterClass.Id.Builder, syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              syft_proto.types.syft.v1.IdOuterClass.Id, syft_proto.types.syft.v1.IdOuterClass.Id.Builder, syft_proto.types.syft.v1.IdOuterClass.IdOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private syft_proto.types.torch.v1.Tensor.TorchTensor tensor_;
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder> tensorBuilder_;
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public boolean hasTensor() {
        return tensorBuilder_ != null || tensor_ != null;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensor getTensor() {
        if (tensorBuilder_ == null) {
          return tensor_ == null ? syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : tensor_;
        } else {
          return tensorBuilder_.getMessage();
        }
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public Builder setTensor(syft_proto.types.torch.v1.Tensor.TorchTensor value) {
        if (tensorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tensor_ = value;
          onChanged();
        } else {
          tensorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public Builder setTensor(
          syft_proto.types.torch.v1.Tensor.TorchTensor.Builder builderForValue) {
        if (tensorBuilder_ == null) {
          tensor_ = builderForValue.build();
          onChanged();
        } else {
          tensorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public Builder mergeTensor(syft_proto.types.torch.v1.Tensor.TorchTensor value) {
        if (tensorBuilder_ == null) {
          if (tensor_ != null) {
            tensor_ =
              syft_proto.types.torch.v1.Tensor.TorchTensor.newBuilder(tensor_).mergeFrom(value).buildPartial();
          } else {
            tensor_ = value;
          }
          onChanged();
        } else {
          tensorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public Builder clearTensor() {
        if (tensorBuilder_ == null) {
          tensor_ = null;
          onChanged();
        } else {
          tensor_ = null;
          tensorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensor.Builder getTensorBuilder() {
        
        onChanged();
        return getTensorFieldBuilder().getBuilder();
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getTensorOrBuilder() {
        if (tensorBuilder_ != null) {
          return tensorBuilder_.getMessageOrBuilder();
        } else {
          return tensor_ == null ?
              syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : tensor_;
        }
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor tensor = 2[json_name = "tensor"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder> 
          getTensorFieldBuilder() {
        if (tensorBuilder_ == null) {
          tensorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder>(
                  getTensor(),
                  getParentForChildren(),
                  isClean());
          tensor_ = null;
        }
        return tensorBuilder_;
      }

      private boolean requiresGrad_ ;
      /**
       * <code>bool requires_grad = 3[json_name = "requiresGrad"];</code>
       */
      public boolean getRequiresGrad() {
        return requiresGrad_;
      }
      /**
       * <code>bool requires_grad = 3[json_name = "requiresGrad"];</code>
       */
      public Builder setRequiresGrad(boolean value) {
        
        requiresGrad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool requires_grad = 3[json_name = "requiresGrad"];</code>
       */
      public Builder clearRequiresGrad() {
        
        requiresGrad_ = false;
        onChanged();
        return this;
      }

      private syft_proto.types.torch.v1.Tensor.TorchTensor grad_;
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder> gradBuilder_;
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public boolean hasGrad() {
        return gradBuilder_ != null || grad_ != null;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensor getGrad() {
        if (gradBuilder_ == null) {
          return grad_ == null ? syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : grad_;
        } else {
          return gradBuilder_.getMessage();
        }
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public Builder setGrad(syft_proto.types.torch.v1.Tensor.TorchTensor value) {
        if (gradBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          grad_ = value;
          onChanged();
        } else {
          gradBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public Builder setGrad(
          syft_proto.types.torch.v1.Tensor.TorchTensor.Builder builderForValue) {
        if (gradBuilder_ == null) {
          grad_ = builderForValue.build();
          onChanged();
        } else {
          gradBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public Builder mergeGrad(syft_proto.types.torch.v1.Tensor.TorchTensor value) {
        if (gradBuilder_ == null) {
          if (grad_ != null) {
            grad_ =
              syft_proto.types.torch.v1.Tensor.TorchTensor.newBuilder(grad_).mergeFrom(value).buildPartial();
          } else {
            grad_ = value;
          }
          onChanged();
        } else {
          gradBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public Builder clearGrad() {
        if (gradBuilder_ == null) {
          grad_ = null;
          onChanged();
        } else {
          grad_ = null;
          gradBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensor.Builder getGradBuilder() {
        
        onChanged();
        return getGradFieldBuilder().getBuilder();
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      public syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder getGradOrBuilder() {
        if (gradBuilder_ != null) {
          return gradBuilder_.getMessageOrBuilder();
        } else {
          return grad_ == null ?
              syft_proto.types.torch.v1.Tensor.TorchTensor.getDefaultInstance() : grad_;
        }
      }
      /**
       * <code>.syft_proto.types.torch.v1.TorchTensor grad = 4[json_name = "grad"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder> 
          getGradFieldBuilder() {
        if (gradBuilder_ == null) {
          gradBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              syft_proto.types.torch.v1.Tensor.TorchTensor, syft_proto.types.torch.v1.Tensor.TorchTensor.Builder, syft_proto.types.torch.v1.Tensor.TorchTensorOrBuilder>(
                  getGrad(),
                  getParentForChildren(),
                  isClean());
          grad_ = null;
        }
        return gradBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:syft_proto.types.torch.v1.Parameter)
    }

    // @@protoc_insertion_point(class_scope:syft_proto.types.torch.v1.Parameter)
    private static final syft_proto.types.torch.v1.ParameterOuterClass.Parameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new syft_proto.types.torch.v1.ParameterOuterClass.Parameter();
    }

    public static syft_proto.types.torch.v1.ParameterOuterClass.Parameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Parameter>
        PARSER = new com.google.protobuf.AbstractParser<Parameter>() {
      @java.lang.Override
      public Parameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Parameter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Parameter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Parameter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public syft_proto.types.torch.v1.ParameterOuterClass.Parameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_syft_proto_types_torch_v1_Parameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_syft_proto_types_torch_v1_Parameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)syft_proto/types/torch/v1/parameter.pr" +
      "oto\022\031syft_proto.types.torch.v1\032!syft_pro" +
      "to/types/syft/v1/id.proto\032&syft_proto/ty" +
      "pes/torch/v1/tensor.proto\"\332\001\n\tParameter\022" +
      ",\n\002id\030\001 \001(\0132\034.syft_proto.types.syft.v1.I" +
      "dR\002id\022>\n\006tensor\030\002 \001(\0132&.syft_proto.types" +
      ".torch.v1.TorchTensorR\006tensor\022#\n\rrequire" +
      "s_grad\030\003 \001(\010R\014requiresGrad\022:\n\004grad\030\004 \001(\013" +
      "2&.syft_proto.types.torch.v1.TorchTensor" +
      "R\004gradb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          syft_proto.types.syft.v1.IdOuterClass.getDescriptor(),
          syft_proto.types.torch.v1.Tensor.getDescriptor(),
        });
    internal_static_syft_proto_types_torch_v1_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_syft_proto_types_torch_v1_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_syft_proto_types_torch_v1_Parameter_descriptor,
        new java.lang.String[] { "Id", "Tensor", "RequiresGrad", "Grad", });
    syft_proto.types.syft.v1.IdOuterClass.getDescriptor();
    syft_proto.types.torch.v1.Tensor.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
