# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft_proto/types/syft/v1/exceptions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft_proto.types.syft.v1 import id_pb2 as pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft_proto/types/syft/v1/exceptions.proto',
  package='pysyft_proto.types.syft.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+pysyft_proto/types/syft/v1/exceptions.proto\x12\x1apysyft_proto.types.syft.v1\x1a#pysyft_proto/types/syft/v1/id.proto\"{\n\x16ResponseSignatureError\x12\x1c\n\ttraceback\x18\x01 \x01(\tR\ttraceback\x12\x43\n\rids_generated\x18\x03 \x03(\x0b\x32\x1e.pysyft_proto.types.syft.v1.IdR\x0cidsGenerated\"5\n\x15SendNotPermittedError\x12\x1c\n\ttraceback\x18\x01 \x01(\tR\ttraceback\"4\n\x14GetNotPermittedError\x12\x1c\n\ttraceback\x18\x01 \x01(\tR\ttracebackb\x06proto3')
  ,
  dependencies=[pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2.DESCRIPTOR,])




_RESPONSESIGNATUREERROR = _descriptor.Descriptor(
  name='ResponseSignatureError',
  full_name='pysyft_proto.types.syft.v1.ResponseSignatureError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traceback', full_name='pysyft_proto.types.syft.v1.ResponseSignatureError.traceback', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='traceback', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ids_generated', full_name='pysyft_proto.types.syft.v1.ResponseSignatureError.ids_generated', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='idsGenerated', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=235,
)


_SENDNOTPERMITTEDERROR = _descriptor.Descriptor(
  name='SendNotPermittedError',
  full_name='pysyft_proto.types.syft.v1.SendNotPermittedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traceback', full_name='pysyft_proto.types.syft.v1.SendNotPermittedError.traceback', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='traceback', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=290,
)


_GETNOTPERMITTEDERROR = _descriptor.Descriptor(
  name='GetNotPermittedError',
  full_name='pysyft_proto.types.syft.v1.GetNotPermittedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traceback', full_name='pysyft_proto.types.syft.v1.GetNotPermittedError.traceback', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='traceback', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=344,
)

_RESPONSESIGNATUREERROR.fields_by_name['ids_generated'].message_type = pysyft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
DESCRIPTOR.message_types_by_name['ResponseSignatureError'] = _RESPONSESIGNATUREERROR
DESCRIPTOR.message_types_by_name['SendNotPermittedError'] = _SENDNOTPERMITTEDERROR
DESCRIPTOR.message_types_by_name['GetNotPermittedError'] = _GETNOTPERMITTEDERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseSignatureError = _reflection.GeneratedProtocolMessageType('ResponseSignatureError', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESIGNATUREERROR,
  '__module__' : 'pysyft_proto.types.syft.v1.exceptions_pb2'
  # @@protoc_insertion_point(class_scope:pysyft_proto.types.syft.v1.ResponseSignatureError)
  })
_sym_db.RegisterMessage(ResponseSignatureError)

SendNotPermittedError = _reflection.GeneratedProtocolMessageType('SendNotPermittedError', (_message.Message,), {
  'DESCRIPTOR' : _SENDNOTPERMITTEDERROR,
  '__module__' : 'pysyft_proto.types.syft.v1.exceptions_pb2'
  # @@protoc_insertion_point(class_scope:pysyft_proto.types.syft.v1.SendNotPermittedError)
  })
_sym_db.RegisterMessage(SendNotPermittedError)

GetNotPermittedError = _reflection.GeneratedProtocolMessageType('GetNotPermittedError', (_message.Message,), {
  'DESCRIPTOR' : _GETNOTPERMITTEDERROR,
  '__module__' : 'pysyft_proto.types.syft.v1.exceptions_pb2'
  # @@protoc_insertion_point(class_scope:pysyft_proto.types.syft.v1.GetNotPermittedError)
  })
_sym_db.RegisterMessage(GetNotPermittedError)


# @@protoc_insertion_point(module_scope)
