# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysyft/types/torch/v1/parameter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pysyft.generic.v1 import tensor_pb2 as pysyft_dot_generic_dot_v1_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pysyft/types/torch/v1/parameter.proto',
  package='pysyft.types.torch.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%pysyft/types/torch/v1/parameter.proto\x12\x15pysyft.types.torch.v1\x1a\x1epysyft/generic/v1/tensor.proto\"\xa2\x01\n\tParameter\x12\x0e\n\x02id\x18\x01 \x01(\x05R\x02id\x12\x31\n\x06tensor\x18\x02 \x01(\x0b\x32\x19.pysyft.generic.v1.TensorR\x06tensor\x12#\n\rrequires_grad\x18\x03 \x01(\x08R\x0crequiresGrad\x12-\n\x04grad\x18\x04 \x01(\x0b\x32\x19.pysyft.generic.v1.TensorR\x04gradb\x06proto3')
  ,
  dependencies=[pysyft_dot_generic_dot_v1_dot_tensor__pb2.DESCRIPTOR,])




_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='pysyft.types.torch.v1.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pysyft.types.torch.v1.Parameter.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='pysyft.types.torch.v1.Parameter.tensor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tensor', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requires_grad', full_name='pysyft.types.torch.v1.Parameter.requires_grad', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='requiresGrad', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grad', full_name='pysyft.types.torch.v1.Parameter.grad', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='grad', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=259,
)

_PARAMETER.fields_by_name['tensor'].message_type = pysyft_dot_generic_dot_v1_dot_tensor__pb2._TENSOR
_PARAMETER.fields_by_name['grad'].message_type = pysyft_dot_generic_dot_v1_dot_tensor__pb2._TENSOR
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'pysyft.types.torch.v1.parameter_pb2'
  # @@protoc_insertion_point(class_scope:pysyft.types.torch.v1.Parameter)
  })
_sym_db.RegisterMessage(Parameter)


# @@protoc_insertion_point(module_scope)
