# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syft_proto/generic/pointers/v1/multi_pointer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from syft_proto.generic.pointers.v1 import pointer_pb2 as syft__proto_dot_generic_dot_pointers_dot_v1_dot_pointer__pb2
from syft_proto.types.syft.v1 import id_pb2 as syft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='syft_proto/generic/pointers/v1/multi_pointer.proto',
  package='syft_proto.generic.pointers.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2syft_proto/generic/pointers/v1/multi_pointer.proto\x12\x1esyft_proto.generic.pointers.v1\x1a,syft_proto/generic/pointers/v1/pointer.proto\x1a!syft_proto/types/syft/v1/id.proto\"\xcf\x01\n\x0cMultiPointer\x12\x39\n\tobject_id\x18\x01 \x01(\x0b\x32\x1c.syft_proto.types.syft.v1.IdR\x08objectId\x12?\n\x0clocation_ids\x18\x02 \x03(\x0b\x32\x1c.syft_proto.types.syft.v1.IdR\x0blocationIds\x12\x43\n\x08pointers\x18\x03 \x03(\x0b\x32\'.syft_proto.generic.pointers.v1.PointerR\x08pointersb\x06proto3')
  ,
  dependencies=[syft__proto_dot_generic_dot_pointers_dot_v1_dot_pointer__pb2.DESCRIPTOR,syft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2.DESCRIPTOR,])




_MULTIPOINTER = _descriptor.Descriptor(
  name='MultiPointer',
  full_name='syft_proto.generic.pointers.v1.MultiPointer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='syft_proto.generic.pointers.v1.MultiPointer.object_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='objectId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_ids', full_name='syft_proto.generic.pointers.v1.MultiPointer.location_ids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='locationIds', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointers', full_name='syft_proto.generic.pointers.v1.MultiPointer.pointers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pointers', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=375,
)

_MULTIPOINTER.fields_by_name['object_id'].message_type = syft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_MULTIPOINTER.fields_by_name['location_ids'].message_type = syft__proto_dot_types_dot_syft_dot_v1_dot_id__pb2._ID
_MULTIPOINTER.fields_by_name['pointers'].message_type = syft__proto_dot_generic_dot_pointers_dot_v1_dot_pointer__pb2._POINTER
DESCRIPTOR.message_types_by_name['MultiPointer'] = _MULTIPOINTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiPointer = _reflection.GeneratedProtocolMessageType('MultiPointer', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPOINTER,
  '__module__' : 'syft_proto.generic.pointers.v1.multi_pointer_pb2'
  # @@protoc_insertion_point(class_scope:syft_proto.generic.pointers.v1.MultiPointer)
  })
_sym_db.RegisterMessage(MultiPointer)


# @@protoc_insertion_point(module_scope)
