// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syft_proto/execution/v1/state.proto

package org.openmined.syftproto.execution.v1;

public final class StateOuterClass {
  private StateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:syft_proto.execution.v1.State)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> 
        getPlaceholdersList();
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder getPlaceholders(int index);
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    int getPlaceholdersCount();
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    java.util.List<? extends org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder> 
        getPlaceholdersOrBuilderList();
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder getPlaceholdersOrBuilder(
        int index);

    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> 
        getTensorsList();
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor getTensors(int index);
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    int getTensorsCount();
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    java.util.List<? extends org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder> 
        getTensorsOrBuilderList();
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder getTensorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code syft_proto.execution.v1.State}
   */
  public  static final class State extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:syft_proto.execution.v1.State)
      StateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use State.newBuilder() to construct.
    private State(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private State() {
      placeholders_ = java.util.Collections.emptyList();
      tensors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new State();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private State(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                placeholders_ = new java.util.ArrayList<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder>();
                mutable_bitField0_ |= 0x00000001;
              }
              placeholders_.add(
                  input.readMessage(org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                tensors_ = new java.util.ArrayList<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor>();
                mutable_bitField0_ |= 0x00000002;
              }
              tensors_.add(
                  input.readMessage(org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          placeholders_ = java.util.Collections.unmodifiableList(placeholders_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          tensors_ = java.util.Collections.unmodifiableList(tensors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmined.syftproto.execution.v1.StateOuterClass.internal_static_syft_proto_execution_v1_State_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmined.syftproto.execution.v1.StateOuterClass.internal_static_syft_proto_execution_v1_State_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmined.syftproto.execution.v1.StateOuterClass.State.class, org.openmined.syftproto.execution.v1.StateOuterClass.State.Builder.class);
    }

    public static final int PLACEHOLDERS_FIELD_NUMBER = 1;
    private java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> placeholders_;
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    public java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> getPlaceholdersList() {
      return placeholders_;
    }
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    public java.util.List<? extends org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder> 
        getPlaceholdersOrBuilderList() {
      return placeholders_;
    }
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    public int getPlaceholdersCount() {
      return placeholders_.size();
    }
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder getPlaceholders(int index) {
      return placeholders_.get(index);
    }
    /**
     * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
     */
    public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder getPlaceholdersOrBuilder(
        int index) {
      return placeholders_.get(index);
    }

    public static final int TENSORS_FIELD_NUMBER = 2;
    private java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> tensors_;
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    public java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> getTensorsList() {
      return tensors_;
    }
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    public java.util.List<? extends org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder> 
        getTensorsOrBuilderList() {
      return tensors_;
    }
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    public int getTensorsCount() {
      return tensors_.size();
    }
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor getTensors(int index) {
      return tensors_.get(index);
    }
    /**
     * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
     */
    public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder getTensorsOrBuilder(
        int index) {
      return tensors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < placeholders_.size(); i++) {
        output.writeMessage(1, placeholders_.get(i));
      }
      for (int i = 0; i < tensors_.size(); i++) {
        output.writeMessage(2, tensors_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < placeholders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, placeholders_.get(i));
      }
      for (int i = 0; i < tensors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tensors_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.openmined.syftproto.execution.v1.StateOuterClass.State)) {
        return super.equals(obj);
      }
      org.openmined.syftproto.execution.v1.StateOuterClass.State other = (org.openmined.syftproto.execution.v1.StateOuterClass.State) obj;

      if (!getPlaceholdersList()
          .equals(other.getPlaceholdersList())) return false;
      if (!getTensorsList()
          .equals(other.getTensorsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlaceholdersCount() > 0) {
        hash = (37 * hash) + PLACEHOLDERS_FIELD_NUMBER;
        hash = (53 * hash) + getPlaceholdersList().hashCode();
      }
      if (getTensorsCount() > 0) {
        hash = (37 * hash) + TENSORS_FIELD_NUMBER;
        hash = (53 * hash) + getTensorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openmined.syftproto.execution.v1.StateOuterClass.State parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.openmined.syftproto.execution.v1.StateOuterClass.State prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code syft_proto.execution.v1.State}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:syft_proto.execution.v1.State)
        org.openmined.syftproto.execution.v1.StateOuterClass.StateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.openmined.syftproto.execution.v1.StateOuterClass.internal_static_syft_proto_execution_v1_State_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.openmined.syftproto.execution.v1.StateOuterClass.internal_static_syft_proto_execution_v1_State_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.openmined.syftproto.execution.v1.StateOuterClass.State.class, org.openmined.syftproto.execution.v1.StateOuterClass.State.Builder.class);
      }

      // Construct using org.openmined.syftproto.execution.v1.StateOuterClass.State.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlaceholdersFieldBuilder();
          getTensorsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (placeholdersBuilder_ == null) {
          placeholders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          placeholdersBuilder_.clear();
        }
        if (tensorsBuilder_ == null) {
          tensors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tensorsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.openmined.syftproto.execution.v1.StateOuterClass.internal_static_syft_proto_execution_v1_State_descriptor;
      }

      @java.lang.Override
      public org.openmined.syftproto.execution.v1.StateOuterClass.State getDefaultInstanceForType() {
        return org.openmined.syftproto.execution.v1.StateOuterClass.State.getDefaultInstance();
      }

      @java.lang.Override
      public org.openmined.syftproto.execution.v1.StateOuterClass.State build() {
        org.openmined.syftproto.execution.v1.StateOuterClass.State result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.openmined.syftproto.execution.v1.StateOuterClass.State buildPartial() {
        org.openmined.syftproto.execution.v1.StateOuterClass.State result = new org.openmined.syftproto.execution.v1.StateOuterClass.State(this);
        int from_bitField0_ = bitField0_;
        if (placeholdersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            placeholders_ = java.util.Collections.unmodifiableList(placeholders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.placeholders_ = placeholders_;
        } else {
          result.placeholders_ = placeholdersBuilder_.build();
        }
        if (tensorsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            tensors_ = java.util.Collections.unmodifiableList(tensors_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tensors_ = tensors_;
        } else {
          result.tensors_ = tensorsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.openmined.syftproto.execution.v1.StateOuterClass.State) {
          return mergeFrom((org.openmined.syftproto.execution.v1.StateOuterClass.State)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.openmined.syftproto.execution.v1.StateOuterClass.State other) {
        if (other == org.openmined.syftproto.execution.v1.StateOuterClass.State.getDefaultInstance()) return this;
        if (placeholdersBuilder_ == null) {
          if (!other.placeholders_.isEmpty()) {
            if (placeholders_.isEmpty()) {
              placeholders_ = other.placeholders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlaceholdersIsMutable();
              placeholders_.addAll(other.placeholders_);
            }
            onChanged();
          }
        } else {
          if (!other.placeholders_.isEmpty()) {
            if (placeholdersBuilder_.isEmpty()) {
              placeholdersBuilder_.dispose();
              placeholdersBuilder_ = null;
              placeholders_ = other.placeholders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              placeholdersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlaceholdersFieldBuilder() : null;
            } else {
              placeholdersBuilder_.addAllMessages(other.placeholders_);
            }
          }
        }
        if (tensorsBuilder_ == null) {
          if (!other.tensors_.isEmpty()) {
            if (tensors_.isEmpty()) {
              tensors_ = other.tensors_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTensorsIsMutable();
              tensors_.addAll(other.tensors_);
            }
            onChanged();
          }
        } else {
          if (!other.tensors_.isEmpty()) {
            if (tensorsBuilder_.isEmpty()) {
              tensorsBuilder_.dispose();
              tensorsBuilder_ = null;
              tensors_ = other.tensors_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tensorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTensorsFieldBuilder() : null;
            } else {
              tensorsBuilder_.addAllMessages(other.tensors_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.openmined.syftproto.execution.v1.StateOuterClass.State parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.openmined.syftproto.execution.v1.StateOuterClass.State) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> placeholders_ =
        java.util.Collections.emptyList();
      private void ensurePlaceholdersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          placeholders_ = new java.util.ArrayList<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder>(placeholders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder> placeholdersBuilder_;

      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> getPlaceholdersList() {
        if (placeholdersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(placeholders_);
        } else {
          return placeholdersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public int getPlaceholdersCount() {
        if (placeholdersBuilder_ == null) {
          return placeholders_.size();
        } else {
          return placeholdersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder getPlaceholders(int index) {
        if (placeholdersBuilder_ == null) {
          return placeholders_.get(index);
        } else {
          return placeholdersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder setPlaceholders(
          int index, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder value) {
        if (placeholdersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceholdersIsMutable();
          placeholders_.set(index, value);
          onChanged();
        } else {
          placeholdersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder setPlaceholders(
          int index, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder builderForValue) {
        if (placeholdersBuilder_ == null) {
          ensurePlaceholdersIsMutable();
          placeholders_.set(index, builderForValue.build());
          onChanged();
        } else {
          placeholdersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder addPlaceholders(org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder value) {
        if (placeholdersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceholdersIsMutable();
          placeholders_.add(value);
          onChanged();
        } else {
          placeholdersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder addPlaceholders(
          int index, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder value) {
        if (placeholdersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceholdersIsMutable();
          placeholders_.add(index, value);
          onChanged();
        } else {
          placeholdersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder addPlaceholders(
          org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder builderForValue) {
        if (placeholdersBuilder_ == null) {
          ensurePlaceholdersIsMutable();
          placeholders_.add(builderForValue.build());
          onChanged();
        } else {
          placeholdersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder addPlaceholders(
          int index, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder builderForValue) {
        if (placeholdersBuilder_ == null) {
          ensurePlaceholdersIsMutable();
          placeholders_.add(index, builderForValue.build());
          onChanged();
        } else {
          placeholdersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder addAllPlaceholders(
          java.lang.Iterable<? extends org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder> values) {
        if (placeholdersBuilder_ == null) {
          ensurePlaceholdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, placeholders_);
          onChanged();
        } else {
          placeholdersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder clearPlaceholders() {
        if (placeholdersBuilder_ == null) {
          placeholders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          placeholdersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public Builder removePlaceholders(int index) {
        if (placeholdersBuilder_ == null) {
          ensurePlaceholdersIsMutable();
          placeholders_.remove(index);
          onChanged();
        } else {
          placeholdersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder getPlaceholdersBuilder(
          int index) {
        return getPlaceholdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder getPlaceholdersOrBuilder(
          int index) {
        if (placeholdersBuilder_ == null) {
          return placeholders_.get(index);  } else {
          return placeholdersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public java.util.List<? extends org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder> 
           getPlaceholdersOrBuilderList() {
        if (placeholdersBuilder_ != null) {
          return placeholdersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(placeholders_);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder addPlaceholdersBuilder() {
        return getPlaceholdersFieldBuilder().addBuilder(
            org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.getDefaultInstance());
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder addPlaceholdersBuilder(
          int index) {
        return getPlaceholdersFieldBuilder().addBuilder(
            index, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.getDefaultInstance());
      }
      /**
       * <code>repeated .syft_proto.execution.v1.Placeholder placeholders = 1[json_name = "placeholders"];</code>
       */
      public java.util.List<org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder> 
           getPlaceholdersBuilderList() {
        return getPlaceholdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder> 
          getPlaceholdersFieldBuilder() {
        if (placeholdersBuilder_ == null) {
          placeholdersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.Placeholder.Builder, org.openmined.syftproto.execution.v1.PlaceholderOuterClass.PlaceholderOrBuilder>(
                  placeholders_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          placeholders_ = null;
        }
        return placeholdersBuilder_;
      }

      private java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> tensors_ =
        java.util.Collections.emptyList();
      private void ensureTensorsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          tensors_ = new java.util.ArrayList<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor>(tensors_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder> tensorsBuilder_;

      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> getTensorsList() {
        if (tensorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tensors_);
        } else {
          return tensorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public int getTensorsCount() {
        if (tensorsBuilder_ == null) {
          return tensors_.size();
        } else {
          return tensorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor getTensors(int index) {
        if (tensorsBuilder_ == null) {
          return tensors_.get(index);
        } else {
          return tensorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder setTensors(
          int index, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor value) {
        if (tensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTensorsIsMutable();
          tensors_.set(index, value);
          onChanged();
        } else {
          tensorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder setTensors(
          int index, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder builderForValue) {
        if (tensorsBuilder_ == null) {
          ensureTensorsIsMutable();
          tensors_.set(index, builderForValue.build());
          onChanged();
        } else {
          tensorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder addTensors(org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor value) {
        if (tensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTensorsIsMutable();
          tensors_.add(value);
          onChanged();
        } else {
          tensorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder addTensors(
          int index, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor value) {
        if (tensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTensorsIsMutable();
          tensors_.add(index, value);
          onChanged();
        } else {
          tensorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder addTensors(
          org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder builderForValue) {
        if (tensorsBuilder_ == null) {
          ensureTensorsIsMutable();
          tensors_.add(builderForValue.build());
          onChanged();
        } else {
          tensorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder addTensors(
          int index, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder builderForValue) {
        if (tensorsBuilder_ == null) {
          ensureTensorsIsMutable();
          tensors_.add(index, builderForValue.build());
          onChanged();
        } else {
          tensorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder addAllTensors(
          java.lang.Iterable<? extends org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor> values) {
        if (tensorsBuilder_ == null) {
          ensureTensorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tensors_);
          onChanged();
        } else {
          tensorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder clearTensors() {
        if (tensorsBuilder_ == null) {
          tensors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tensorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public Builder removeTensors(int index) {
        if (tensorsBuilder_ == null) {
          ensureTensorsIsMutable();
          tensors_.remove(index);
          onChanged();
        } else {
          tensorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder getTensorsBuilder(
          int index) {
        return getTensorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder getTensorsOrBuilder(
          int index) {
        if (tensorsBuilder_ == null) {
          return tensors_.get(index);  } else {
          return tensorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public java.util.List<? extends org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder> 
           getTensorsOrBuilderList() {
        if (tensorsBuilder_ != null) {
          return tensorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tensors_);
        }
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder addTensorsBuilder() {
        return getTensorsFieldBuilder().addBuilder(
            org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.getDefaultInstance());
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder addTensorsBuilder(
          int index) {
        return getTensorsFieldBuilder().addBuilder(
            index, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.getDefaultInstance());
      }
      /**
       * <code>repeated .syft_proto.execution.v1.StateTensor tensors = 2[json_name = "tensors"];</code>
       */
      public java.util.List<org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder> 
           getTensorsBuilderList() {
        return getTensorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder> 
          getTensorsFieldBuilder() {
        if (tensorsBuilder_ == null) {
          tensorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensor.Builder, org.openmined.syftproto.execution.v1.StateTensorOuterClass.StateTensorOrBuilder>(
                  tensors_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          tensors_ = null;
        }
        return tensorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:syft_proto.execution.v1.State)
    }

    // @@protoc_insertion_point(class_scope:syft_proto.execution.v1.State)
    private static final org.openmined.syftproto.execution.v1.StateOuterClass.State DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.openmined.syftproto.execution.v1.StateOuterClass.State();
    }

    public static org.openmined.syftproto.execution.v1.StateOuterClass.State getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<State>
        PARSER = new com.google.protobuf.AbstractParser<State>() {
      @java.lang.Override
      public State parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new State(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<State> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<State> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.openmined.syftproto.execution.v1.StateOuterClass.State getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_syft_proto_execution_v1_State_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_syft_proto_execution_v1_State_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#syft_proto/execution/v1/state.proto\022\027s" +
      "yft_proto.execution.v1\032*syft_proto/execu" +
      "tion/v1/state_tensor.proto\032)syft_proto/e" +
      "xecution/v1/placeholder.proto\032&syft_prot" +
      "o/types/torch/v1/tensor.proto\"\221\001\n\005State\022" +
      "H\n\014placeholders\030\001 \003(\0132$.syft_proto.execu" +
      "tion.v1.PlaceholderR\014placeholders\022>\n\007ten" +
      "sors\030\002 \003(\0132$.syft_proto.execution.v1.Sta" +
      "teTensorR\007tensorsB&\n$org.openmined.syftp" +
      "roto.execution.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openmined.syftproto.execution.v1.StateTensorOuterClass.getDescriptor(),
          org.openmined.syftproto.execution.v1.PlaceholderOuterClass.getDescriptor(),
          org.openmined.syftproto.types.torch.v1.Tensor.getDescriptor(),
        });
    internal_static_syft_proto_execution_v1_State_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_syft_proto_execution_v1_State_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_syft_proto_execution_v1_State_descriptor,
        new java.lang.String[] { "Placeholders", "Tensors", });
    org.openmined.syftproto.execution.v1.StateTensorOuterClass.getDescriptor();
    org.openmined.syftproto.execution.v1.PlaceholderOuterClass.getDescriptor();
    org.openmined.syftproto.types.torch.v1.Tensor.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
